package org.example.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.example.cayenne.persistent.Parametr;
import org.example.cayenne.persistent.TypesOfParameter;
import org.example.cayenne.persistent.Value;

/**
 * Class _Izdelie was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Izdelie extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Parametr> PARAMETR = Property.create("parametr", Parametr.class);
    public static final Property<TypesOfParameter> TYPES_OF_PARAMETER = Property.create("typesOfParameter", TypesOfParameter.class);
    public static final Property<List<Value>> VALUES = Property.create("values", List.class);

    public void setParametr(Parametr parametr) {
        setToOneTarget("parametr", parametr, true);
    }

    public Parametr getParametr() {
        return (Parametr)readProperty("parametr");
    }


    public void setTypesOfParameter(TypesOfParameter typesOfParameter) {
        setToOneTarget("typesOfParameter", typesOfParameter, true);
    }

    public TypesOfParameter getTypesOfParameter() {
        return (TypesOfParameter)readProperty("typesOfParameter");
    }


    public void addToValues(Value obj) {
        addToManyTarget("values", obj, true);
    }
    public void removeFromValues(Value obj) {
        removeToManyTarget("values", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Value> getValues() {
        return (List<Value>)readProperty("values");
    }


}
