package org.example.cayenne.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.example.cayenne.persistent.Parametr;

/**
 * Class _MetaParams was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MetaParams extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_META_PARAMETRA_PK_COLUMN = "ID_META_PARAMETRA";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Parametr>> PARAMETRS = Property.create("parametrs", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToParametrs(Parametr obj) {
        addToManyTarget("parametrs", obj, true);
    }
    public void removeFromParametrs(Parametr obj) {
        removeToManyTarget("parametrs", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Parametr> getParametrs() {
        return (List<Parametr>)readProperty("parametrs");
    }


}
